### ISSUE TITLE
Plugin does not seem to listen to config

### ISSUE THREAD

**Issue by gerard76** [matomo-org/plugin-DeviceDetectorCache#14]
My config:
```
head -n25 config.ini.php 
; <?php exit; ?> DO NOT REMOVE THIS LINE
; file automatically generated or modified by Matomo; you can manually override the default values in global.ini.php by redefining them in this file.
[database]
host = "***"
username = "matomo"
password = "***"
dbname = "matomo"

[General]
force_ssl = 1
salt = "89a3676b1e60866d0638704623716a**"
trusted_hosts[] = "***"
trusted_hosts[] = "***"
trusted_hosts[] = "***"

[DeviceDetectorCache]
access_log_path = "/var/log/nginx/access.log"
access_log_regex = "/^(\S+) (\S+) (\S+) \[([^:]+):(\d+:\d+:\d+) ([^\]]+)\] \"(\S+) (.*?) (\S+)\" (\S+) (\S+) \"([^\"]*)\" \"([^\"]*)\"$/"
regex_match_entry = 14
num_cache_entries = 200000

[Plugins]
Plugins[] = "CorePluginsAdmin"
Plugins[] = "CoreAdminHome"
Plugins[] = "CoreHome"
```

Running `php ./console  device-detector-cache:warm-cache -vvv`

Gives me the error:
<img width="547" alt="Screenshot 2020-10-08 at 15 15 30" src="https://user-images.githubusercontent.com/765547/95463525-23212680-0979-11eb-9e9a-d4f2a1ef8dc2.png">

**Comment by tsteur** [comment]
Hi @gerard76 are you using this with Matomo 3 or Matomo 4?

**Comment by gerard76** [comment]
3.14.1

**Comment by gerard76** [comment]
~~Let me upgrade that~~
I thought I accidentally installed an old version.

**Comment by tsteur** [comment]
@gerard76 I just checked again and this should work. We're using it as well and works nice for us. For some reason it seems to use the default value for the access log path instead of your configured path for the nginx access log file.

Any chance you have maybe a multi server setup and the config file was for example not updated everywhere? Or maybe the config file contains another section `[DeviceDetectorCache]`?

**Comment by gerard76** [comment]
Garghhh. Activating the plugin added the lines! I thought I had to add them and did...sorry to have bothered you. Thanks for pointing me in the right direction.
